
require("davey.plugins-setup")
require("davey.core.options")
require("davey.core.keymaps")
require("davey.core.colorscheme")
require("davey.plugins.comment")
require("davey.plugins.nvim-tree")
require("davey.plugins.lualine")
require("davey.plugins.telescope")
require("davey.plugins.nvim-cmp")
require("davey.plugins.lsp.mason")
require("davey.plugins.lsp.lspsaga")
require("davey.plugins.lsp.lspconfig")
require("davey.plugins.lsp.null-ls")
require("davey.plugins.treesitter")
